[tool.black]
target-version = ['py311']
line-length = 100

[tool.pytest.ini_options]
testpaths = [ "tests/" ]
pythonpath = "hotpulse/"
addopts = "--tb=short -q"

[tool.isort]
profile = "black"
src_paths = ["hotpulse/", "tests/"]
line_length = 100

[tool.mypy]
python_version = "3.11"
strict = true
check_untyped_defs = true
warn_unused_configs = true
ignore_missing_imports = true
warn_unused_ignores = false

[tool.pydeps]
reverse = true
rankdir = "BT"

[tool.coverage.run]
relative_files = true
source = [ "hotpulse/" ]
omit = [
    "hotpulse/app_version.py",
    "hotpulse/cli_app/*",
]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@(abc\\.)?abstractmethod",
    "@unittest\\.skip",
    "raise NotImplementedError",
]
